
cart:
    path:     /cart
    defaults: { _controller: TransactionsGestionCommandeBundle:Default:cart }

checkout:
    path:     /checkout
    defaults: { _controller: TransactionsGestionCommandeBundle:Default:checkout }