<?php

namespace Encheres\GestionEncheresBundle\Repository;

/**
 * EncheresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EncheresRepository extends \Doctrine\ORM\EntityRepository
{
}
