<?php

namespace Encheres\GestionEncheresBundle\Repository;

/**
 * JournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JournalRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')->where('u.idSession IN (:id)')
            ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
    }

    public function getMise($id_session)
    {
        $conn = $this->getEntityManager()->getConnection();

        //il faut recuperer par cette requete l'url de l'utilisateur , son nom , la date de la mise , la derniere mise
          //l'etat de la session et l'id du gangant dans l'ordre croissant par la date de la derniere mise des 5 ou 4 dernieres mises .




        $sql = '
        SELECT date_mise,id_client,mise,derniere_mise
        FROM journal j , session s
        WHERE j.id_session= :id and s.id= :id and j.mise != 0 
        ORDER BY date_mise DESC 
        LIMIT 4
         ';


        $stmt = $conn->prepare($sql);
        $stmt->execute(['id'=>$id_session]);
        return $stmt->fetchAll();
    }

}
