<?php

namespace Encheres\GestionEncheresBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getEncheresId($id_prd,$idProprietaire,$seuilmise,$seuilparticipants)
           {
               $conn = $this->getEntityManager()->getConnection();

               $sql = '
        SELECT id_encheres FROM encheres  
        WHERE id_cible= :id_prd and seuil_mise= :seuilmise 
        and seuil_participants= :seuilparticipants and id_proprietaire= :idProprietaire';

               $stmt = $conn->prepare($sql);
               $stmt->execute([
                   'id_prd'=>$id_prd,
                   'seuilmise'=>$seuilmise,
                   'seuilparticipants'=>$seuilparticipants,
                   'idProprietaire'=>$idProprietaire
               ]);

               return $stmt->fetch();
           }
}
