<?php

namespace Store\GestionProduitsBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function filtreCat($id)
    {
        $query = $this->getEntityManager()->createQuery("select p from StoreGestionProduitsBundle:Produit p WHERE p.idCategorie=:id")
            ->setParameter('id',$id);
        return $query->getResult();


    }
}
