<?php

namespace Transactions\GestionCommandeBundle\Repository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLast($id)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = '
        SELECT id
        FROM commande 
        WHERE id_client= :id ORDER BY id DESC   ';

        $stmt = $conn->prepare($sql);
        $stmt->execute(['id'=>$id]);
        return $stmt->fetch();
    }

}
