<?php

namespace Transactions\GestionCommandeBundle\Repository;

/**
 * LignecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignecommandeRepository extends \Doctrine\ORM\EntityRepository
{
    public function findArray($id)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')->where('u.idCommande IN (:id)')
            ->setParameter('id',$id);
        return $qb->getQuery()->getResult();
    }
}
