<?php

namespace Transactions\GestionCommandeBundle\Repository;

/**
 * PanierItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PanierItemRepository extends \Doctrine\ORM\EntityRepository
{
}
