<?php

namespace Veterinaire\GestionRDVBundle\Repository;

/**
 * Rdv_veterinaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rdv_veterinaireRepository extends \Doctrine\ORM\EntityRepository
{
}
