<?php

namespace Reclamation\DresseurReclamationBundle\Repository;

/**
 * AnimalsdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalsdfRepository extends \Doctrine\ORM\EntityRepository
{
}
