<?php

namespace Reclamation\DresseurReclamationBundle\Repository;

/**
 * AnimalperduRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimalperduRepository extends \Doctrine\ORM\EntityRepository
{
}
