<?php

namespace Reclamation\DresseurReclamationBundle\Repository;

/**
 * Rdv_dresseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rdv_dresseurRepository extends \Doctrine\ORM\EntityRepository
{
}
