encheres_gestion_encheres_homepage:
    path:     /
    defaults: { _controller: EncheresGestionEncheresBundle:Default:index }
enchereAdmin:
    path:     /enchereAdmin
    defaults: { _controller: EncheresGestionEncheresBundle:admin:enchereAdmin }
