<?php

namespace Association\GestionAssociationBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function DQL($a)
    {
        $query = $this->getEntityManager()->createQuery("select e from AssociationGestionAssociationBundle:Evenement:Evenement e WHERE e.id_association=:a")
            ->setParameter('a',$a);
        return $query->getResult();
    }

    public function trierEvenement()
    {
        $query = $this->getEntityManager()->createQuery("select e from AssociationGestionAssociationBundle:Evenement:Evenement e order BY e.nom");

        return $query->getResult();
    }

    public function trierEvenementNombre()
    {
        $query = $this->getEntityManager()->createQuery("select e from AssociationGestionAssociationBundle:Evenement:Evenement e order BY e.nbrParticipants DESC ");

        return $query->getResult();
    }

    public function filtreCat($id)
    {
        $query = $this->getEntityManager()->createQuery("select e from AssociationGestionAssociationBundle:Evenement e  WHERE e.id_categorie=:a") ->setParameter('a',$id);

        return $query->getResult();
    }


}
