<?php

namespace Association\GestionAssociationBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
   /* public function reserver($id,$uid)
    {
        $query = $this->getEntityManager()->createQuery("select p from AssociationGestionAssociationBundle:Participation p  WHERE p.id_client=:a and p.id_evenement=:b") ->setParameter('a',$id)->setParameter('b',$uid);

        return $query->getResult();
    }*/

    public function reserver($uid,$ide)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = '
        SELECT *
        FROM participation 
        WHERE id_client= :uid AND id_evenement= :ide  ';

        $stmt = $conn->prepare($sql);
        $stmt->execute(['uid'=>$uid,'ide'=>$ide]);
        return $stmt->fetch();
    }
}
